### PR TITLE
Changed all the icons

### PR DESCRIPTION
**Pull request by Blisterexe**
Keep in mind this isnt perfect, the scaling might be messed up so i might come back to clean it up later.

New app icon:
AppIcon

### CODE REVIEW

**Comment by Blisterexe** [comment]
I will fix the anti-aliasing issue on the desktop icon tommorow morning

**Comment by JW-CH** [comment]
Thank you for your contribution. Could you add a folder with the icons/images? Immich has a `design`-Folder that contains images. Maybe this is something we could do too?

**Comment by 3rob3** [comment]
> Thank you for your contribution. Could you add a folder with the icons/images? Immich has a `design`-Folder that contains images. Maybe this is something we could do too?

Do you mean in addition to the project specific images? Because Android requires them in a specific location.

**Comment by JW-CH** [comment]
> > Thank you for your contribution. Could you add a folder with the icons/images? Immich has a `design`-Folder that contains images. Maybe this is something we could do too?
> 
> Do you mean in addition to the project specific images? Because Android requires them in a specific location.

Exactly. Also, to have the SVG etc. in a specific place.

**Comment by Blisterexe** [comment]
@JW-CH want me to take care of that?

**Comment by JW-CH** [comment]
> @JW-CH want me to take care of that?

yes, please add the 'source'-files to a folder that makes sense, something like `design`

**Comment by Blisterexe** [comment]
> > @JW-CH want me to take care of that?
> 
> yes, please add the 'source'-files to a folder that makes sense, something like `design`

Done!

**Pull request merged**
