### PR TITLE
Feat: Weather UI

### PR DESCRIPTION
**Pull request by JW-CH**
- Move weather logic to backend
- New weather UI

*TODO*
- Add more SVG-Icons for weather (currently alway sunny icon)

image

### CODE REVIEW

**Comment by 3rob3** [comment]
Nice! What's the limitation with weather icons?

**Comment by JW-CH** [comment]
> Nice! What's the limitation with weather icons?

No limitation, I think svg-icons would look gread / fit the ui more. Need to find some nice SVGs.

**Comment by JW-CH** [comment]
image

@3rob3 I am thinking about no icons at all. What do you think?

**Comment by 3rob3** [comment]
> image
> 
> @3rob3 I am thinking about no icons at all. What do you think?

I like it, looks clean. Can always add them in later if you/others want.

**Pull request merged**
