### PR TITLE
Add text-shadow to app.css to improve readability

### PR DESCRIPTION
**Pull request by iCanHazSkillz**
Addresses suggestion made in request #198

### CODE REVIEW

**Comment by JW-CH** [comment]
Thank you for your contribution. We are mostly using tailwind for our CSS. What are your thoughts on a custom CSS file that you can map to your container to edit/override and customize your immichFrame?

**Comment by iCanHazSkillz** [comment]
Thank you! I went ahead and created 2 classes to accommodate shadows on both small and large text and applied it to the clock as well.

Let me know if there should be anything else added.

**Comment by JW-CH** [comment]
I think there happened something when pulling from main. Your code contains some of the new stuff but not everything and does not build anymore :P

**Comment by JW-CH** [comment]
Replaced by #232

**Comment by 3rob3** [comment]
this looks really nice, thanks! A lot easier to see/read now.

**Pull request closed without merging**
